### DISCUSSION TITLE
How to check all files in a repository containing "centralized" renovatebot configuration?

### DISCUSSION THREAD

**Discussion by kastl-ars** [renovatebot/pre-commit-hooks#2981] [Q&A] [answered]
Dear maintainers,

we have a repository that holds `*.json` files containing different renovate configurations. Those files are being referred to in other repos using `extends`, i.e. we have only one line in each repo's `renovate.json`.

So it would be crucial to not mess up the centralized configuration files. I would like to use pre-commit as one part (and a GitlabCI pipeline later).

How would I supply the list of files to check with the pre-commit hook?

I found the `RENOVATE_CONFIG_FILE`  variable in the docs, but how would I set it in the `.pre-commit-config.yaml`? Can I use a wildcard (`*.json`)?

Thanks in advance!

Kind Regards,
Johannes

**Comment by maxbrunet** [comment, marked as answer]
The [`files`](https://pre-commit.com/#config-files) key of the hook can simply be overridden in the `.pre-commit-config.yaml`

**Comment by kastl-ars** [comment]
Thanks, I will give this a try.

**Reply by norman-zon** [reply]
Did it work for you? I tried setting 

```yaml
repos:
  - repo: https://github.com/renovatebot/pre-commit-hooks
    rev: 41.37.9
    hooks:
      - id: renovate-config-validator
        files: '.*\.json$'

```

but my preset in `folder/mypreset.json` is ignored: 

```sh
renovate-config-validator............................(no files to check)Skipped
```
