### ISSUE TITLE
Can you make this work for `default.json` too?

### ISSUE THREAD

**Issue by paddyroddy** [renovatebot/pre-commit-hooks#1458]
I would like to validate my parent config, currently it only works for the form of `'(^|/).?renovate(?:rc)?(?:\.json5?)?$'`

**Comment by paddyroddy** [comment]
Worked it out, can just do
```yaml
- repo: https://github.com/renovatebot/pre-commit-hooks
  rev: 37.12.0
  hooks:
    - id: renovate-config-validator
      args: [default.json]
```
