### ISSUE TITLE
Docs request: use of `--strict`

### ISSUE THREAD

**Issue by jamesbraza** [renovatebot/pre-commit-hooks#2464]
I think it's useful to mention in the `README` that `--strict` can be passed for a tighter configuration:

```yaml
repos:
  - repo: https://github.com/renovatebot/pre-commit-hooks
    rev: 38.126.1
    hooks:
      - id: renovate-config-validator
        args: [--strict]
```
